This tests the ``add_integer`` function from the ``0-add_integer`` module.

Normal usage
============
>>> add_integer = __import__('0-add_integer').add_integer
>>> add_integer(2, 3)
5

>>> add_integer(2.0, 3)
5

>>> add_integer(2, 3.0)
5

>>> add_integer(2.0, 3.0)
5


Raise a TypeError exception
===========================
>>> add_integer('2', 3)
Traceback (most recent call last):
...............
TypeError: a must be an integer

>>> add_integer(2.0, '3')
Traceback (most recent call last):
................
TypeError: b must be an integer


Raise an OverflowError exception
================================
>>> add_integer(2e110000, 0.1)
Traceback (most recent call last):
...............
OverflowError: result is too large

>>> add_integer(2, 3e110000)
Traceback (most recent call last):
...............
OverflowError: result is too large

>>> add_integer(2e110000, 3e110000)
Traceback (most recent call last):
...............
OverflowError: result is too large
